# Generated by Django 3.1.2 on 2021-08-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_auto_20210818_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.CharField(blank=True, choices=[('Cacti & Succulents', 'Cacti & Succulents'), ('Foliage', 'Foliage'), ('Flowering Plants', 'Flowering Plants'), ('Vegetables', 'Vegetables'), ('Herbs', 'Herbs')], max_length=30, null=True),
        ),
    ]
