# Generated by Django 3.1.2 on 2021-08-20 06:47

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_plant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='last_watered',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date.today)]),
        ),
    ]
