# Generated by Django 3.1.2 on 2021-08-20 08:16

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_auto_20210820_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='last_watered',
            field=models.DateField(default=datetime.date(2021, 8, 20), validators=[django.core.validators.MaxValueValidator(datetime.date.today)]),
        ),
    ]
