# Generated by Django 3.1.2 on 2021-08-20 08:18

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0008_auto_20210820_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='last_watered',
            field=models.DateField(default=django.utils.timezone.now, validators=[django.core.validators.MaxValueValidator(datetime.date.today)]),
        ),
    ]
