# Generated by Django 3.1.2 on 2021-08-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0009_auto_20210820_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='watering_period',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
