# Generated by Django 3.1.2 on 2021-08-20 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0010_auto_20210820_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='plant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plant_notes', to='plants.plant'),
        ),
    ]
