# Generated by Django 3.1.2 on 2021-08-27 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0012_fertilizing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizing',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_fertilizings', to='plants.plant'),
        ),
    ]
