# Generated by Django 3.1.2 on 2021-08-28 07:16

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0013_auto_20210827_0446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repotting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField(default=3)),
                ('last_repotted', models.DateField(default=django.utils.timezone.now, validators=[django.core.validators.MaxValueValidator(datetime.date.today)])),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_repottings', to='plants.plant')),
            ],
        ),
    ]
