# Generated by Django 3.1.2 on 2021-08-29 06:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0014_repotting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizing',
            name='period',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='plant',
            name='watering_period',
            field=models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='repotting',
            name='period',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
