# Generated by Django 3.2.7 on 2021-09-01 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0015_auto_20210829_0617'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
